services:
  postgres:
    image: postgres:16-alpine
    container_name: rating-engine-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: rating_user
      POSTGRES_PASSWORD: rating_pass
      POSTGRES_DB: rating_engine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: