"""add match stage

Revision ID: 722881b2b26c
Revises: c411a1c1a4ce
Create Date: 2026-08-04 13:07:05.442357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722881b2b26c'
down_revision: Union[str, Sequence[str], None] = 'c411a1c1a4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('stage', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'stage')
    # ### end Alembic commands ###
