"""create matches, players, events, ratings

Revision ID: c411a1c1a4ce
Revises: 
Create Date: 2026-07-27 16:00:30.969130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c411a1c1a4ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statsbomb_match_id', sa.Integer(), nullable=False),
    sa.Column('competition', sa.String(length=120), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=True),
    sa.Column('home_team', sa.String(length=120), nullable=False),
    sa.Column('away_team', sa.String(length=120), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_statsbomb_match_id'), 'matches', ['statsbomb_match_id'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statsbomb_player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('primary_position', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_statsbomb_player_id'), 'players', ['statsbomb_player_id'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statsbomb_event_id', sa.String(length=64), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('second', sa.Integer(), nullable=False),
    sa.Column('location_x', sa.Float(), nullable=True),
    sa.Column('location_y', sa.Float(), nullable=True),
    sa.Column('under_pressure', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_match_id'), 'events', ['match_id'], unique=False)
    op.create_index(op.f('ix_events_minute'), 'events', ['minute'], unique=False)
    op.create_index(op.f('ix_events_player_id'), 'events', ['player_id'], unique=False)
    op.create_index(op.f('ix_events_statsbomb_event_id'), 'events', ['statsbomb_event_id'], unique=True)
    op.create_table('player_match_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_match_ratings_match_id'), 'player_match_ratings', ['match_id'], unique=False)
    op.create_index(op.f('ix_player_match_ratings_player_id'), 'player_match_ratings', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_match_ratings_player_id'), table_name='player_match_ratings')
    op.drop_index(op.f('ix_player_match_ratings_match_id'), table_name='player_match_ratings')
    op.drop_table('player_match_ratings')
    op.drop_index(op.f('ix_events_statsbomb_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_player_id'), table_name='events')
    op.drop_index(op.f('ix_events_minute'), table_name='events')
    op.drop_index(op.f('ix_events_match_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_players_statsbomb_player_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_statsbomb_match_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
